on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Determine git SHA short
      id: determine-sha-short
      run: 'echo "::set-output name=git-sha-short::${GITHUB_SHA::7}"'

    - name: Build and push
      id: docker_build
      env:
        DOCKER_BASE_TAG: jeanpinzon/deasy-example
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.DOCKER_BASE_TAG }}:${{ steps.determine-sha-short.outputs.git-sha-short }},${{ env.DOCKER_BASE_TAG }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      env:
        VERSION: ${{ steps.determine-sha-short.outputs.git-sha-short }}
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.2
        command: apply -f k8s.yml